name: Deploy FastAPI to Azure Web Apps (No Docker)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create startup command
        run: |
          echo "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app" > startup.sh
          chmod +x startup.sh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "num-classifier-api"  # Replace with your Azure App name
          package: "."
